### ISSUE TITLE
BluetoothClassic request for post 2.0.0 feature - can we look at how to synchronize requests across the cluster?

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#110]
Once all the dust has settled with 2.0.0, I was wondering if we could look at how we can improve timing of requests for hcitool commands across the cluster. I'm sure you've had similar thoughts and would be interested if these have any merit.

I think at the moment the leader interrogates all of the nodes synchronously, one after another.

I was thinking that if we are already at home, we could request a hcitool check from all nodes simultaneously, bringing down room detection time considerably if you have large number of RA nodes.

This approach would probably sharpen up 'home' detection too, but for home detection we could do even better by distributing each nodes hcitool check across the interval required for a single poll e.g. if we have 6 nodes, call one, wait a sec, call the next etc.  So we are looking for new devices on a more continuous basis.  Some device are better than others for home detection ,e.g. closer to front or back door, so that could come into play.

Thanks for everything!

**Comment by mKeRix** [comment]
There is certainly room for improvement here, it does add more complexity to the algorithm though. Currently the leader gives all nodes something to do in 6s intervals. Two limitations apply: a tracked device can only be accessed by one instance at a time to get good RSSI readings and an instance can only query a single device at a time. There still is considerable surplus time when devices are actually found though - here the queries usually return within 2s. With the remaining 4s we could also query another device to speed up the process. The question that's left for me is how to keep this in sync with the other limitation.

**Comment by Alfiegerner** [comment]
> an instance can only query a single device at a time

Is there a reason for this limitation?  I'm wondering if it is feasible to for the leader to send a request to all devices simultaneously (e.g. async call for each peerAddress) , if so then the total time for all nodes could be bought down to 6 secs. Appreciate it might not be possible, or if it is that there's a fair amount of re-work.

**Comment by mKeRix** [comment]
That is actually the way the algorithm is designed to work - every 6s [distributeInquiries](https://github.com/mKeRix/room-assistant/blob/master/src/integrations/bluetooth-classic/bluetooth-classic.service.ts#L139) is called, which then runs its logic if the node is the leader. In the function a "task map" is created, that states "node a should query address a" etc. The tasks are rotated around with each call. Then it either executes the [local RSSI request function](https://github.com/mKeRix/room-assistant/blob/master/src/integrations/bluetooth-classic/bluetooth-classic.service.ts#L79) or sends an event to the specific node. While `Array.prototype.forEach` is [synchronous in JS](https://stackoverflow.com/questions/5050265/javascript-node-js-is-array-foreach-asynchronous), the RSSI request and cluster functionality is async. This means that the nodes are executing their request at (almost) the same time.

The limitation that an instance can only query a single device at a time is caused by the underlying `hcitool`. The `hcitool cc` command blocks the Bluetooth interface because it retries the connection command x amount of times. Digging deeper into Bluez it executes [hci_send_req](https://github.com/r10r/bluez/blob/master/lib/hci.c#L1083) with `to` (timeout) set to 25000. I think the interval of 6s can be decreased - we don't really care about connecting anyway, we just want the RSSI. For that something like 2s should be enough in most scenarios I guess. But to achieve this we would have to use the Bluetooth socket directly on the device, which complicates the code. Something I can look into in the future at least.

Regardless, with my current concept of Bluetooth (on Linux) I don't think we can send connection requests to multiple addresses at once from a single Bluetooth adapter. I guess you could parallelize things with multiple adapters (e.g. USB sticks), but that might mess with the signal strength due to interference.

**Comment by Alfiegerner** [comment]
Ah okay, thank you for explaining for me. It sound like it should be working optimally, however it does appear to be processing each node sequentially:

Here's my output from: `sudo journalctl -u room-assistant.service -f | grep ALEX_MAC`
```
 9:01:59 AM   [BluetoothClassicService] Querying for RSSI of ALEX_MAC using hcitool
 9:01:59 AM   [BluetoothClassicService] Received RSSI of -19.2 for ALEX_MAC from kitchen
 9:02:12 AM   [BluetoothClassicService] Received RSSI of -20 for ALEX_MAC from office
 9:02:17 AM   [BluetoothClassicService] Received RSSI of -20.8 for ALEX_MAC from playroom
 9:02:29 AM   [BluetoothClassicService] Received RSSI of -23.3 for ALEX_MAC from bathroom
 9:02:35 AM   [BluetoothClassicService] Received RSSI of -27.2 for ALEX_MAC from boys_bedroom
 9:02:41 AM   [BluetoothClassicService] Received RSSI of -6.3 for ALEX_MAC from living_room
 9:02:47 AM   [BluetoothClassicService] Querying for RSSI of ALEX_MAC using hcitool
 9:02:48 AM   [BluetoothClassicService] Received RSSI of -6.9 for ALEX_MAC from kitchen
 9:02:59 AM   [BluetoothClassicService] Received RSSI of -15.9 for ALEX_MAC from office
 9:03:06 AM   [BluetoothClassicService] Received RSSI of -20.3 for ALEX_MAC from playroom
 9:03:18 AM   [BluetoothClassicService] Received RSSI of -27.2 for ALEX_MAC from bathroom
 9:03:24 AM   [BluetoothClassicService] Received RSSI of -25.7 for ALEX_MAC from boys_bedroom
 9:03:29 AM   [BluetoothClassicService] Received RSSI of -4.1 for ALEX_MAC from living_room
 9:03:35 AM   [BluetoothClassicService] Querying for RSSI of ALEX_MAC using hcitool
 9:03:36 AM   [BluetoothClassicService] Received RSSI of -2.9 for ALEX_MAC from kitchen
 9:03:48 AM   [BluetoothClassicService] Received RSSI of -16 for ALEX_MAC from office
 9:03:54 AM   [BluetoothClassicService] Received RSSI of -24.8 for ALEX_MAC from playroom
 9:04:06 AM   [BluetoothClassicService] Received RSSI of -26.4 for ALEX_MAC from bathroom
 9:04:13 AM   [BluetoothClassicService] Received RSSI of -23.9 for ALEX_MAC from boys_bedroom
 9:04:17 AM   [BluetoothClassicService] Received RSSI of -1.3 for ALEX_MAC from living_room
```

Looking at the distributeEnquires method (and apologies I might have the wrong end of the stick here) , as clusterService.send is async I would expect the responses from each node to come in closer together and possibly in a more unordered fashion. The intervals and order of the node processing make it look like some sequential processing is at play.   

I should say I'm extremely happy with the current result - it's an awesome application - just interested in making it making as performant as possible,  Thanks for everything.

**Comment by mKeRix** [comment]
Ah, I see what you mean. That is actually happens because of the other limitation:

> a tracked device can only be accessed by one instance at a time to get good RSSI readings

With only one device configured it's essentially consequential. The relevant code bits for this are in [mapArrays](https://github.com/mKeRix/room-assistant/blob/master/src/integrations/bluetooth-classic/bluetooth-classic.service.ts#L371), which gets passed a list of nodes and addresses. The larger list is reduced to the size of the smaller list to have a 1:1 mapping (based on the offset).

This logic comes from my own testing early on, in the first versions all instances queried a device at the same time. I saw that this led to some wild RSSI variations, which made room presence detection on top of that difficult. But since then a lot has changed in the code base... so maybe it's worth it to investigate this once more.

**Comment by Alfiegerner** [comment]
@mKeRix  - thanks for your consideration of this.  A nice to have but everything in general working very nice already! :)

**Comment by Alfiegerner** [comment]
Choosing this issue as false negatives no longer seen.
