### ISSUE TITLE
[Docker] Command failed: hcitool info "DC:44:B6:XX:XX:XX"

### ISSUE THREAD

**Issue by Tim-Dixon** [mKeRix/room-assistant#114]
**Describe the bug**
I noticed that on both Hassio and Docker itself using docker-compose, I receive the following error:
```
Room-Assistant    | [Nest] 1   - 02/25/2020, 6:18:03 PM   [BluetoothClassicService] Command failed: hcitool info "DC:44:B6:AA:6F:E4"
Room-Assistant    | Can't create connection: I/O error
Room-Assistant    |  +12437ms
Room-Assistant    | Error: Command failed: hcitool info "DC:44:B6:AA:6F:E4"
Room-Assistant    | Can't create connection: I/O error
Room-Assistant    |
Room-Assistant    |     at ChildProcess.exithandler (child_process.js:303:12)
Room-Assistant    |     at ChildProcess.emit (events.js:311:20)
Room-Assistant    |     at maybeClose (internal/child_process.js:1021:16)
Room-Assistant    |     at Socket.<anonymous> (internal/child_process.js:443:11)
Room-Assistant    |     at Socket.emit (events.js:311:20)
Room-Assistant    |     at Pipe.<anonymous> (net.js:668:12)
```

**To reproduce**
Hass.io(Home Assistnat) or Plain Docker w/Compose on Ubuntu 18.04 Server. I'm using a Belkin USB Bluetooth Adapter. 

**Relevant configuration**

```global:
  instanceName: Living_Room
  integrations:
    - bluetoothClassic
    - homeAssistant

cluster:
#  networkInterface: wlan0
  weight: 10
  port: 6425
  peerAddresses:
   - 172.16.24.201:6425
   - 172.16.24.200:6425
homeAssistant:
  mqttUrl: mqtt://172.16.24.254:1883

bluetoothClassic:
  minRssi: -60
  addresses:
    - 'DC:44:B6:XX:XX:XX'
```

**Expected behavior**
Room-Assistant to scan and detect the above referenced MAC if it's present. 

**Environment**
 - room-assistant version: 2.0.0
 - installation type: Docker, Hass.io
 - hardware: Belkin USB Bluetooth Adapter 
 - OS: Ubuntu 18.04 LTS Server

**Additional context**

Oddly it previously had worked fine, but I hadn't recived this error. Now the error is persistent on restart/recreation of the addon/container. I have't updated anything. I did install the required packaged per Docker section of wiki.

**Comment by Tim-Dixon** [comment]
Screenshot showing USB Device Recognized
![image](https://user-images.githubusercontent.com/10284999/75277485-17ac3100-57d6-11ea-938c-37105c4a1e34.png)

**Comment by gbdavidx** [comment]
Did you set the network mode to host??
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus Did y

**Comment by Tim-Dixon** [comment]
My config is as follows:
![image](https://user-images.githubusercontent.com/10284999/75279826-504e0980-57da-11ea-95e1-85ba81e2a078.png)

**Comment by Tim-Dixon** [comment]
![image](https://user-images.githubusercontent.com/10284999/75280178-f00b9780-57da-11ea-9d34-5979d1c8fe1e.png)

**Comment by mKeRix** [comment]
Thanks for the detailed input! From your screenshots everything seems to be correct on the host machine. Are you receiving this error only for "hcitool info" or also for "hcitool cc"?

The info command is just used to set a friendly name and the manufacturer in Home Assistant, but it shouldn't actually impact the room presence functionality. Currently this command can fail due to the device being busy with other things, then the MAC is just used as the name. Is the state changing to the Docker/Hass.io node still? Or is that not working at all now?

**Comment by CoMPaTech** [comment]
If I run (pi 0w's) in verbose mode then I see about the same happening from time to time.
Would you benefit from having more details?

**Comment by dcgrove** [comment]
Hello, I am experiencing this to I believe. My detection totally fails after a period of time on all three of my nodes and the only way to  Is there a way to pipe the output to a file? This is a small sampling of the errors I am getting and it is giving me this on all five of the devices I am trying to track. 

`[Nest] 31100   - 02/26/2020, 8:23:20 AM   [BluetoothClassicService] Querying for RSSI of F0:C3:71:2B:8A:74 using hcitool
[Nest] 31100   - 02/26/2020, 8:23:25 AM   [BluetoothClassicService] Command failed: hcitool cc "F0:C3:71:2B:8A:74" && hcitool rssi "F0:C3:71:2B:8A:74"
Can't create connection: Input/output error
Not connected.

[Nest] 31100   - 02/26/2020, 8:23:26 AM   [BluetoothClassicService] Querying for RSSI of E4:50:EB:0C:DA:91 using hcitool
[Nest] 31100   - 02/26/2020, 8:23:31 AM   [BluetoothClassicService] Command failed: hcitool cc "E4:50:EB:0C:DA:91" && hcitool rssi "E4:50:EB:0C:DA:91"
Can't create connection: Input/output error
Not connected.

`

**Comment by mKeRix** [comment]
@CoMPaTech If it's just about the info command then it's all good, I believe I know the issue. Can be fixed, but shouldn't block anything else.

@dcgrove That is very peculiar (albeit a slightly different issue than the one mentioned here I believe). This really points to an issue with the local Bluetooth antenna on the devices. It seems to get hung up on something. Just out of interest, when this is happening, does running `sudo hciconfig hci0 reset` on the same device (with room-assistant still running!) help?

**Comment by Tim-Dixon** [comment]
@mKeRix I tried 'hcitool cc' with my devices address and it gives me the same result. However I can say that the issue seems to be intermittent. Sometimes the instance operates normally and I only get the dig and unhandled promise warning, but I still get the functionality. Running 'sudo hciconfig hci0 reset'(with Room Assistant running) seemed to immediately resolve the issue, as my device updated as being recognized by the instance in question, which I also happen to be closest to usually for testing, and it is weighted as the leader.

**Comment by mKeRix** [comment]
That sounds like something is confusing or blocking the Bluetooth socket then, interesting. I'll try to work on some changes in this direction tomorrow and will then report back here.

**Comment by dcgrove** [comment]
@mKeRix I ran the command you gave me on two different nodes and it resulted in this error:

```
-bash: kernel:[35950.941767]: command not found
pi@officepi:~/room-assistant/config $
pi@officepi:~/room-assistant/config $ Message from syslogd@officepi at Feb 26 23:21:48 ...
-bash: Message: command not found
pi@officepi:~/room-assistant/config $  kernel:[35950.941784] 5fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
-bash: kernel:[35950.941784]: command not found
pi@officepi:~/room-assistant/config $
pi@officepi:~/room-assistant/config $ Message from syslogd@officepi at Feb 26 23:21:48 ...
-bash: Message: command not found
pi@officepi:~/room-assistant/config $  kernel:[35950.941800] 5fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
-bash: kernel:[35950.941800]: command not found
pi@officepi:~/room-assistant/config $
pi@officepi:~/room-assistant/config $ Message from syslogd@officepi at Feb 26 23:21:48 ...
-bash: Message: command not found
pi@officepi:~/room-assistant/config $  kernel:[35950.943316] Code: e24cb004 e8900088 e1a04000 e1a00003 (e5938010)
-bash: syntax error near unexpected token `('
pi@officepi:~/room-assistant/config $
[1] 0:bash*                                           "officepi" 08:25 27-Feb-20`

```

Incidentally, all of my devices have shown as not_home since 11:22PM CST last night. I haven't run the command on the third node and this is what is being outputted. 

`
[Nest] 501   - 02/27/2020, 8:29:35 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:29:41 AM   [BluetoothClassicService] Querying for RSSI of C8:3C:85:67:9E:86 using hcitool
[Nest] 501   - 02/27/2020, 8:29:41 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:29:47 AM   [BluetoothClassicService] Querying for RSSI of undefined using hcitool
[Nest] 501   - 02/27/2020, 8:29:47 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:29:53 AM   [BluetoothClassicService] Querying for RSSI of E4:50:EB:0C:DA:91 using hcitool
[Nest] 501   - 02/27/2020, 8:29:53 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:29:59 AM   [BluetoothClassicService] Querying for RSSI of 88:64:40:7B:60:89 using hcitool
[Nest] 501   - 02/27/2020, 8:29:59 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:30:05 AM   [BluetoothClassicService] Querying for RSSI of E4:E4:AB:D9:AB:09 using hcitool
[Nest] 501   - 02/27/2020, 8:30:05 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:30:11 AM   [BluetoothClassicService] Querying for RSSI of C8:3C:85:67:9E:86 using hcitool
[Nest] 501   - 02/27/2020, 8:30:11 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 501   - 02/27/2020, 8:30:17 AM   [BluetoothClassicService] Querying for RSSI of undefined using hcitool
[Nest] 501   - 02/27/2020, 8:30:17 AM   [BluetoothClassicService] spawn ENOMEM

[0] 0:node*                                            "FamLRPi" 08:30 27-Feb-20`

I am currently running all three of my nodes with the output piped to a txt file. When/if it stops working again, I will have the complete log at that point.
Thanks!

**Comment by mKeRix** [comment]
@dcgrove I‘ll check the command above tomorrow, when I have access to my APIs again. As for the third node: it’s running out of memory. Can you check what’s taking up all the memory on there?

**Comment by dcgrove** [comment]
@mKeRix it is a pi zeroW. All that is running is room-assistant in a tmux window. I don't have anything else installed.

**Comment by dcgrove** [comment]
@mKeRix 

![image](https://user-images.githubusercontent.com/22239966/75481695-0e9f9900-5969-11ea-8456-5971e8c32ab5.png)

**Comment by mKeRix** [comment]
@Tim-Dixon Could you try v2.1.0 and see if that resolves your issues? Note that for your Docker instance you will need to add the `NET_ADMIN` capability to reap the benefits, like so:

```yaml
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    network_mode: host
    cap_add:
      - NET_ADMIN
```

**Comment by B-Hartley** [comment]
Hi,  I'm on 2.1.1 and seeing similar errors....
raspberry pi zero w - installed following the instructions.  

```
[Nest] 20961   - 03/04/2020, 10:05:59 AM   [BluetoothClassicService] Querying for RSSI of 8C:86:1E:CE:6F:AB using hcitool
[Nest] 20961   - 03/04/2020, 10:06:04 AM   [BluetoothClassicService] Command failed: hcitool -i hci0 cc "8C:86:1E:CE:6F:AB" && hcitool -i hci0 rssi "8C:86:1E:CE:6F:AB"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

[Nest] 20961   - 03/04/2020, 10:06:05 AM   [BluetoothClassicService] Querying for RSSI of 8C:86:1E:CE:6F:AB using hcitool
[Nest] 20961   - 03/04/2020, 10:06:10 AM   [BluetoothClassicService] Command failed: hcitool -i hci0 cc "8C:86:1E:CE:6F:AB" && hcitool -i hci0 rssi "8C:86:1E:CE:6F:AB"
Can't create connection: Input/output error
Get connection info failed: No such file or directory
```

**Comment by mKeRix** [comment]
@B-Hartley This error is a bit different. Try to run the command manually in the shell and see if it's the same output, also make sure that the Bluetooth adapter is running (execute `hciconfig`, output should list that hci0 is up and running).

**Comment by B-Hartley** [comment]
ok, did a clean install on all 6 of my pi zeros.
Getting the in/out errors.

tried running commands manually....

```
pi@zero-6:~/room-assistant $ hcitool -i hci0 cc "CC:D2:81:40:2B:DB"
Can't create connection: Input/output error
pi@zero-6:~/room-assistant $ 
pi@zero-6:~/room-assistant $ hcitool -i hci0 rssi "CC:D2:81:40:2B:DB"
Get connection info failed: No such file or directory
pi@zero-6:~/room-assistant $ hciconfig
hci0:   Type: Primary  Bus: UART
        BD Address: B8:27:EB:C5:EC:B6  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:17048 acl:54 sco:0 events:757 errors:0
        TX bytes:8323 acl:54 sco:0 commands:446 errors:0

```

Tried:
`
sudo hciconfig hci0 reset`

then the same commands, same result.
If I run from a service without the -v. it does seem to run successfully sometimes.
Not sure how to get the full logs when it is running normally?

How can I help you investigate this ?

config file on all 6 nodes is.....
(with weights different on each)

```
global:
  instanceName: conservatory
  integrations:
    - bluetoothClassic
    - homeAssistant
cluster:
  autoDiscovery: false
  quorum: 4
  weight: 6
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
bluetoothClassic:
  minRssi: -20
  addresses:
    - 'CC:D2:81:xx:xx:xx'
    - '8C:86:1E:xx:xx:xx'
    - '2C:33:61:xx:xx:xx'
    - '2C:33:61:xx:xx:xx'
    - '18:55:E3:xx:xx:xx'
homeAssistant:
  mqttUrl: mqtt://192.168.xx.xxx:1883
  mqttOptions:
    username: mqtt_xxxx
    password: xxxxxxxx
```

**Comment by mKeRix** [comment]
@B-Hartley You can get the service logs with `journalctl -u room-assistant.service`, but I think the logs will probably look similar to the other ones we saw above.

@B-Hartley @xehn The errors you're seeing most likely just point to the Bluetooth devices not responding to requests - they are even normal when the device isn't in reach (which is why they're only logged to debug), but of course shouldn't happen the whole time. As there are a lot of different Bluetooth devices out there it's really hard to find the issue. Just out of interest, does running `hcitool -I hci0 cc --role=s "xx:xx:xx:xx:xx:xx" && hcitool -i hci0 rssi "xx:xx:xx:xx:xx:xx"` also result in the same output?

**Comment by xehn** [comment]
@mKeRix Thanks for the response - I just tested on three machines (pi zero w, pi 3b, and an i5 nuc) and got the same responses on all three:
```
Can't create connection: Input/output error
Get connection info failed: No such file or directory
```
For what it is worth, I tried doing an `hciconfig hci0 reset` first, but got the same result.  I also rebooted one machine and tried again after a fresh boot, but again, same error.
Running both commands as superuser returns the same error with slightly different wording: 
```
$ sudo hcitool -i hci0 cc --role=s "xx:xx:xx:xx:xx:xx" && sudo hcitool -i hci0 rssi "xx:xx:xx:xx:xx:xx"
Can't create connection: Input/output error
Read RSSI failed: Input/output error
```
Googling around on this error mostly seems to be people looking to use BTLE (rather than classic).  Could this have something to do with the way bluetooth is implemented on each device?  

@B-Hartley - perhaps it would be helpful for us to state what our _client_ devices are as well?

For my purposes, I am using a Pixel 3 XL and two Pixel 3a devices.  Since all three of mine likely use the same chip and software stack, it would seem prudent to test against another manufacturer.  I will do this tonight and report back.

**Comment by B-Hartley** [comment]
My clients are all iPhones.
iPhone 11 Pro
iPhone 11 proMax (or whatever it is called)
iPhone 7 (I think)
iPhone 7 Max. (I think)

**Comment by xehn** [comment]
Checking back in - different manufacturer client (an older Kyocera) same error.  I also tried zeroing out the mac address - didn't expect it to connect to anything, obviously, just wanted to see what would happen.  Got the same pause, and the same error messages.
```
$ hcitool -i hci0 cc --role=s "00:00:00:00:00:00" && hcitool -i hci0 rssi "00:00:00:00:00:00"

Get connection info failed: No such file or directory
```
Not sure what to try next.

**Comment by mKeRix** [comment]
iPhones should definitely work - I've tested with my own devices and others have reported success as well. Bluetooth needs to be on in control center and settings, maybe the device also can't be in energy saver mode (untested).

Let's try going a level deeper and looking at the raw HCI data. You can install `hcidump` with `sudo apt-get install bluez-hcidump`, then open another shell/tmux window and run `sudo hcidump`. Then go back to your original shell and type `sudo hcitool cc "xx:xx:xx:xx:xx:xx" && sudo hcitool rssi "xx:xx:xx:xx:xx:xx"`. I would love to see what the output of `hcidump` is for you after running the connection/rssi command.

When testing with my personal iPhone I see a connect complete followed by a few read features, finally ending in a disconnect. For a non-existent MAC I just see page timeouts.

**Comment by xehn** [comment]
```
$ sudo hcidump
HCI sniffer - Bluetooth packet analyzer ver 5.43
device: hci0 snap_len: 1500 filter: 0xffffffff
< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr xx:xx:xx:xx:xx:xx ptype 0xcc18 rswitch 0x01 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
> HCI Event: Connect Complete (0x03) plen 11
    status 0x04 handle 12 bdaddr xx:xx:xx:xx:xx:xx type ACL encrypt 0x00
    Error: Page Timeout
< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr xx:xx:xx:xx:xx:xx ptype 0xcc18 rswitch 0x01 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
> HCI Event: Connect Complete (0x03) plen 11
    status 0x04 handle 12 bdaddr xx:xx:xx:xx:xx:xx type ACL encrypt 0x00
    Error: Page Timeout
< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr xx:xx:xx:xx:xx:xx ptype 0xcc18 rswitch 0x01 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr xx:xx:xx:xx:xx:xx ptype 0xcc18 rswitch 0x01 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x0b ncmd 1
    Error: ACL Connection Already Exists
< HCI Command: Read RSSI (0x05|0x0005) plen 2
    handle 0
> HCI Event: Command Complete (0x0e) plen 7
    Read RSSI (0x05|0x0005) ncmd 1
    status 0x02 handle 0 rssi 0
    Error: Unknown Connection Identifier
> HCI Event: Connect Complete (0x03) plen 11
    status 0x04 handle 12 bdaddr xx:xx:xx:xx:xx:xx type ACL encrypt 0x00
    Error: Page Timeout
< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr xx:xx:xx:xx:xx:xx ptype 0xcc18 rswitch 0x01 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
> HCI Event: Connect Complete (0x03) plen 11
    status 0x04 handle 12 bdaddr xx:xx:xx:xx:xx:xx type ACL encrypt 0x00
    Error: Page Timeout
```
(Above is unedited with the exception of regexing out mac addresses) 

I left hcidump going for awhile, ran the command manually in another shell (with present and non-present addresses), as well as letting room-assistant run in the background.  

If any different methodologies would help, let me know and I'm happy to run them.

I can see a couple different error messages above, mostly timeouts (which I am assuming are normal when a device is out of range), and that 'unknown connection identifier' showed up once.  I am remote now, so will do some more testing when I get home tonight - just wanted to get you what I could for now.


Thanks again for the help with this!

**Comment by buhochileno** [comment]
Hi, I have exactly the same problem!...how is this close!? :-) ...can you tell me if you fix it and how?

Thanks!

Mauricio

**Comment by gbdavidx** [comment]
Found a uwb kit that supports apple devies. Going to try that. Gave up on
this project

**Comment by drnichols** [comment]
Also having this issue with RA on pi zero having rebuilt the issue persists. Frustrating as it was working previously but now needs a reboot daily for detection to work.

**Comment by mKeRix** [comment]
@drnichols Did you upgrade Bluez recently? If so, try out the steps mentioned in #661 - might be related.
