### ISSUE TITLE
Request: update new room-assistant versions across cluster

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#118]
**Is your feature request related to a problem? Please describe.**
Currently each upgrade required manual npm -i for each node in the cluster.  Very possible to end up with different peers on different versions if you have several peers.

**Describe the solution you'd like**
Would be awesome if updates could either happen automatically, or updated to the version of the leader, or updated to a version in a global config, e.g.  in a shared default.yml.

**Describe alternatives you've considered**
As above.

**Comment by gmalbert** [comment]
@Alfiegerner that's a great idea! Given all of these quick updates (which are very much appreciated), that'd be a huge time saver.

**Comment by mKeRix** [comment]
I agree, it's a fantastic idea. Not sure if it's doable for Docker containers, but I suppose the vast majority of installs will be pure NodeJS on Pi Zeros anyway. I'll put this high on the list of things to try, just so that the update process will be easier in the future.

**Comment by gmalbert** [comment]
Good point about Docker! I wonder if it could be solved by specifying IP addresses for the update.

**Comment by mKeRix** [comment]
What do you think about using a provisioning tool like Ansible for this? We could provide a playbook that people could then just execute with the version/configs that they want and the provisioning tool would take care of setting everything up. It's an additional tool to setup, but it keeps the complexity out of the actual software and also makes way more things doable.

**Comment by gmalbert** [comment]
@mKeRix you certainly have a better sense of added complexity than we do. If it doesn't make sense to integrate it, but there's a tool that can do it, I'm all for that.

**Comment by Alfiegerner** [comment]
@mKeRix , yup that sounds sensible, will be interested to see what it looks like.

**Comment by mKeRix** [comment]
I built Ansible playbooks that make this possible this weekend, there also is a [quickstart guide](https://www.room-assistant.io/guide/quickstart-ansible.html) available. The playbook will essentially run through all the steps in the other quickstart guides automatically, so that you can setup new devices from scratch completely automated. It is also capable of managing configs from a central location for you. Whenever you re-run the playbook it will distribute the configs and update room-assistant across the cluster.

In theory you should be able to also apply this to hosts with everything already installed, the install steps should just be skipped (marked as "ok") in this case. The playbook makes a few assumptions though: configs are put into `~/room-assistant/config/` and it runs room-assistant as a service with the unit file located at `/etc/systemd/system/room-assistant.service`.

This should hopefully make managing your installs much easier. Let me know if you have any feedback!
