### ISSUE TITLE
Clean install on pi-zero w problems?

### ISSUE THREAD

**Issue by B-Hartley** [mKeRix/room-assistant#129]
**Describe the bug**
room-assistant not in /usr/local/bin/

**To reproduce**
I decided to do a clean install on the pi zero to make sure I had the best chance of room-assistant working.
so, I did this.....

Raspian lite install by imaging sd.
wpa_supplicant.conf for wifi
ssh file for ssh access
```

apt-get update
apt-get upgrade

```
under pi user, installed node using....

`wget https://raw.githubusercontent.com/grayda/node-pi-zero/master/install-node-v10.15.0.sh -O /tmp/install-node-v10.15.0.sh && source /tmp/install-node-v10.15.0.sh
`

```
sudo apt-get install libavahi-compat-libdnssd-dev
sudo npm i --global --unsafe-perm room-assistant

```

Should I have installed node under the root account?
or sudo'd the install of node?

did I do something else wrong?

the binary is available in /opt/nodejs/bin/
should I just run It from there?

thoughts?

Thanks.

**Comment by mKeRix** [comment]
On the Pi Zero the NodeJS installation is a bit different, that's why you see it being linked to a different directory. This is totally normal though. Just launch it with the full path (`/opt/nodejs/bin/room-assistant`) or add the bin folder to your `PATH` (see step 3 of the [quickstart installation](https://www.room-assistant.io/guide/quickstart-pi-zero-w.html#installing-room-assistant)).

**Comment by B-Hartley** [comment]
Thanks for the response.  I think I must have followed this the first time, then lost my mind when I was doing it again.  Sorry for wasting your time.  I'll get them all setup cleanly again and see if they will stay running reliably.  Thanks !
