### ISSUE TITLE
simultaneous BLE and BT Classic

### ISSUE THREAD

**Issue by tehbra1n** [mKeRix/room-assistant#139]
This is more a question than an issue that I wanted to get confirmation on.  On the RPI Zero W, is it possible to monitor both BLE and BT Classic devices at the same time?  I'm pretty sure from reading the docs that that requires two BT adapters in the system running room-assistant, but I wasn't sure if the RPI Zero W might have that out of the box.  In my environment, they do seem to be mutually exclusive but I wanted to confirm before I dug any deeper.

On a related note, assuming they are mutually exclusive and I'm using only Android phones, would running an app like nRF Connect on the Android devices provide BLE advertisements there?  I had hoped to combine Android phones with iBeacons for presence detection.

So far running room-assistant on 3 RPI Zero W's using BT Classic is working great using just the phones!

**Comment by mKeRix** [comment]
It's not possible out of the box, you would need one of those cheap USB Bluetooth sticks (and most likely a microUSB to USB adapter) to get both working at the same time. Apps like nRF Connect would work for detecting phones with BLE, given that the phone supports it of course. There it's just important to ensure the app is always running. I think other users posted some power saving options they had to change so that the app doesn't get killed in the background occasionally.

**Comment by tehbra1n** [comment]
perfect, thanks!
