### ISSUE TITLE
Transmit processed i2c data wirelessly for a clean presence sensor install

### ISSUE THREAD

**Issue by THATDONFC** [mKeRix/room-assistant#144]
**Is your feature request related to a problem? Please describe.**
I would like to put a gridEye sensor up in the corner of a room but don't want to mount my pi up there.

**Describe the solution you'd like**
I understand I can put a pi zero w up there with the sensor. BUT, the sensor is SO small, it would be great if I could put this into an enclosure with say a WEMOS D1 Mini. The wemos could process the i2c data and send it to the pi.

I'm not sure how feasible this is. I know you can't send i2c data wirelessly. But it is my understanding that if you can process the data, you can then send that processed data wirelessly.

**Comment by THATDONFC** [comment]
I got the gridEye working on the bench using the pi at my desk. The tracker works really well @mKeRix!

I've got a pi zero w on the way to put this up in a corner. I came across a [Pedestrian Counter](https://github.com/CityofEdmonton/pedestrian-counter) while looking into these amg8833 sensors. This could be a great addition to room-assistant. Mount one of these sensors over a doorway and you can start counting the people entering or leaving the room. This is the ultimate occupancy detection imo.

**Comment by mKeRix** [comment]
I agree that mounting these sensors with an ESP is much easier and nicer due to the smaller size - I don't think that it's in the scope of room-assistant though. Everything that room-assistant does to calculate the presence based off heat data can also be done on the ESP directly and then sent along. I think this feature request is much better suited for the [esphome](https://github.com/esphome/esphome) project. Just needs someone to port the sensor communication and detection logic to a component there.

Setting it up as a counter is an interesting concept, the GridEye sensor also should have a high enough resolution for this. I don't think I will get to implementing this anytime soon, but if you want I can take a look at that in the future. As that's different from the initial feature request in this issue I would ask you to open a new issue for that if you want to keep that tracked.
