### ISSUE TITLE
Identifying devices

### ISSUE THREAD

**Issue by Amir974** [mKeRix/room-assistant#15]
Hi!

I got this code to work for me and it seems like some awesome data is picked up - my problem is I can't tell which devices are being tracked :(

I'd love to know how you Identify the devices you want to track if there is a simple trick for that...

**Comment by Amir974** [comment]
Should I be able to find my iPad / iPhone / Apple watch with this thing ?

**Comment by mKeRix** [comment]
Honestly right now the best way is to either know the Bluetooth MAC address or just move the tag around and check the console output (with the console publisher on) to see which moved. In an early version it would print out the name of the accessories if they supplied it, however I may have removed this at some point... I should probably take a look at that.

The problem with Apple devices is that they [randomize their MAC address in the most recent versions](http://apple.stackexchange.com/questions/216742/do-ios8-devices-randomize-bluetooth-mac-address). They do this specifically to prevent people from tracking you, for privacy reasons. That also means you can't track yourself natively though.

I found an app called "Cubeacon Tools" that supposedly allows you transmit ibeacons (which you can track with the ibeacon scanner), but your mileage may vary. I haven't tried it myself. If you don't mind sticking a little tag somewhere you can get those Bluetooth finder tags foir pretty cheap. I use Radbeacon Dots for configurability, but any of those Bluetooth 4.x tags work really.

Once we somehow find a solution for tracking your actual phone I'll be sure to let you know... I sure as hell would love that too.

**Comment by Amir974** [comment]
I am currently setup to use MAC's and I still don't see the iPhone's true MAC address (which I can get from the settings app)...

I also tried pairing the pi with the iPhone using [this method ](https://www.cnet.com/how-to/how-to-setup-bluetooth-on-a-raspberry-pi-3/) but still it does not seem to help establish a reliable "relationship" between them...

If you come across anything I can test, please let me know!

**Comment by Amir974** [comment]
@mKeRix I might have just had a Urika moment...
you said Apple devices randomize their mac... what if - instead of looking for MACs we count them?
can you create a separate topic with the count of device who were last discovered in the approved range?

If I can count the number of unknown devices for example (the ones not listed on the white list) who were discovered in the past minute (or n minutes) - it would be a safe bet these are the devices I am looking for (or better yet create a separate list of devices to be excluded of the count)

It's not full proof BUT it can give some great input for automation if you can pull that off :)

**Comment by mKeRix** [comment]
Pairing doesn't help in this case due to how the component is setup. I don't think you can do proper multiroom tracking through pairing... at least from my understanding. Proper tracking of an iPhone could be done with an app listening on beacons (essentially reversing the current workflow) and broadcasting updates to HASS itself. Some stores do this with e.g. special offers on arriving, but I haven't found any good setups for private use in this regard yet.

Counting them would work, at least assuming you always take care of your blacklists. It's quite an interesting idea for sure. I need to finish some other stuff this weekend but I'll definitely dig into this as soon as I find some time!

**Comment by Amir974** [comment]
Hi There!
Any luck with the count feature ?

**Comment by mKeRix** [comment]
Haven't found the time for this yet, currently have it set as a todo for Saturday. Sorry!

**Comment by vswraith** [comment]
Would love this feature 👍

**Comment by mKeRix** [comment]
Update: currently have my hands full with work and a Thesis, will only have time for this again starting around the middle of July. Super sorry for dragging this out so long :(

**Comment by vswraith** [comment]
As a workaround, I saw this script- https://github.com/ewenchou/bluetooth-proximity this gets the same MAC everytime. But it does not give distance. Any way to reuse this code?

**Comment by gruijter** [comment]
I have setup a rpi3 to monitor BLE/iBeacon devices in my home. But I have a problem when I want to track both iBeacons and other BLE devices (like my Xiaomi Mi smartwatch).

The ble-tracker of room-assistant has the problem of finding the random mac-addresses of iBeacon devices. This means that I'm practically unable to track iPhones/iPads/iBeacons of family members when using the ble-tracker. It also means I cannot filter them out / ignore them, since the address changes all the time. I tried setting the ble-tracker to UUID in stead of MAC, but I still get the macs (just formatted without the :'s ).

If I enable the iBeacon tracker I do seem to get UUID's, but only from iBeacon devices. Thus I'm not receiving all the other BLE devices that I want to track (like my Xiaomi Mi smart watch)

And when I enable both iBeacon and ble tracker, I get flooded with messages from both channels, but I cannot correlate the iBeacon message with the (unwanted) ble message of the same iBeacon device.

So can anyone tell me how to set up my room-assistant to track both ble-devices and iBeacons, but filter out the unwanted random macs from iBeacons?

Thanks in advance!

**Comment by k1ng440** [comment]
set maxDistance to 1 and put the device you want to identify next to your rpi.
