### ISSUE TITLE
Apple watch 5 

### ISSUE THREAD

**Issue by macguy81** [mKeRix/room-assistant#164]
**Describe the bug**
I have two iPhones and one Google pixel that works flawlessly but for some reason it does not detect Apple watch 5 

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

global:
  instanceName: Officeroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.149.118:1883'
  mqttOptions:
    username: XXX
    password: XXX
bluetoothClassic:
  minRssi: -20
  addresses:
    - 'E4:50:XX:XX:XX:XX'
    - 'b0:2a:XX:XX:XX:XX'
    - '50:7A:XX:XX:XX:XX'
    - '98:CA:33:25:DB:82'

**Expected behavior**

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi Zero W, NUC]
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**

**Comment by mKeRix** [comment]
Does `hcitool cc <watch-mac> && hcitool rssi <watch-mac>` return an RSSI for your watch? Also verify the MAC is the correct Bluetooth MAC and Bluetooth is turned on. I believe the watch also can't be in power reserve mode for it to be accessible via BT.

**Comment by macguy81** [comment]
i get the following message Can't create connection: Input/output error
Read RSSI failed: Input/output error

**Comment by mKeRix** [comment]
Did you run the command while room-assistant was running? Because that might have caused the results you posted. If not: something's off with the Bluetooth on the Pi. Check that the hci device is up with `hciconfig`, maybe run a firmware update using `rpi-update`.

**Comment by macguy81** [comment]
I tried it with room-addistant off and same message, i am running this on a linux server on my dell laptop not on pi

**Comment by macguy81** [comment]
i also tried it on pi and still cannot get my apple watch 5 detected

**Comment by mKeRix** [comment]
Maybe check for kernel updates on your laptop? Unfortunately this is a hardware or OS issue, nothing room-assistant can do about this. It's also quite hard to debug. You can also get some more in-depth Bluetooth logs using `hcidump` as described [here](https://github.com/mKeRix/room-assistant/issues/114#issuecomment-597284729). That might help track down the issue.

**Comment by paulrbeers** [comment]
@macguy81 Do you have any bluetooth devices paired to your Apple Watch?   I couldn't get tracking to work on my Apple Watch 2 until I paired a set of headphones to it (and then promptly paired them back to my phone), but for whatever reason it "woke up" my Bluetooth on my watch and has been tracking fine ever since (with the exception of one of my nodes seems to over power all others...)

**Comment by macguy81** [comment]
> @macguy81 Do you have any bluetooth devices paired to your Apple Watch? I couldn't get tracking to work on my Apple Watch 2 until I paired a set of headphones to it (and then promptly paired them back to my phone), but for whatever reason it "woke up" my Bluetooth on my watch and has been tracking fine ever since (with the exception of one of my nodes seems to over power all others...)


This worked great as soon as i paired the headset it started working on room-assistant, thanks for ur help!!!!!!!!!!

**Comment by buhochileno** [comment]
Pairing doesn't help in my case, I been trying to track pretty much anything on my network without help...I pretty sure is a OS/Kernel/bluez issue and not RA, ...can't find a working solution anyway..I will love to be able to download a raspberry os version + packages where this bluez thing works,,,from what I read this dependency in a hcitool is the main problem since is kind of deprecated and it seems developers are pushing for others tools that provide same functionalities, ...as far as I understand RA use hcitool to scan for device signals, I was able to get that info on the same raspberry that hcitool gives problems with other commands, but since RA depends on hcitool I pretty much stock...

**Comment by mKeRix** [comment]
@buhochileno Did you take a look at the pinned #661 already? There also is an open feature request issue for providing a pre-built image that you can simply flash (#506), but there are no concrete plans for it yet. The dependency on hcitool is something that I'd like to drop at some point as well, unfortunately this isn't as easy as the equivalent modern tool behaves in a way that it would break the BT Classic flow in RA. I have another idea of what I want to try, but that's still very much in the future as well.
