### ISSUE TITLE
API shows different measuredPower value for the same device.

### ISSUE THREAD

**Issue by marrold** [mKeRix/room-assistant#211]
**Describe the bug**

I am querying the API to view the RSSIs and Measured Power for different BLE devices, however one device is showing different measuredPower on each node. I'd expect this to be the same. 

**To reproduce**

I am transmitting an iBeacon with the Android app "Beacon Simulator". Tx Power is set to `-85`, Transmission Power is set to `-75`

**Relevant configuration**

curl http://10.0.130.122:6415/entities | jq .

```
  {
    "attributes": {
      "distance": 1.2,
      "lastUpdatedAt": "2020-06-04T11:17:47.020Z"
    },
    "id": "ble-2f234454cf6d4a0fadf2f4911ba9ffa6-1-1",
    "name": "2f234454cf6d4a0fadf2f4911ba9ffa6-1-1 Room Presence",
    "distributed": true,
    "distances": {
      "kitchen": {
        "lastUpdatedAt": "2020-06-04T11:17:28.916Z",
        "distance": 2.4,
        "outOfRange": false
      },
      "bedroom": {
        "lastUpdatedAt": "2020-06-03T10:40:28.807Z",
        "distance": 2.8,
        "outOfRange": false
      },
      "lounge": {
        "lastUpdatedAt": "2020-06-04T11:17:47.020Z",
        "distance": 1.2,
        "outOfRange": false
      }
    },
    "timeout": 90,
    "measuredValues": {
      "kitchen": {
        "rssi": -78.98693145963486,
        "measuredPower": -70
      },
      "bedroom": {
        "rssi": -97.81422610986179,
        "measuredPower": -85
      },
      "lounge": {
        "rssi": -79.26978518066068,
        "measuredPower": -77
      }
    },
    "state": "lounge"
  }
```

**Expected behavior**
I'd usually expect measuredpower  to remain the same.

**Environment**
 - room-assistant version: Latest
 - installation type: Docker
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian

**Comment by mKeRix** [comment]
Are you setting tag overrides for the `measuredPower` on the nodes by any chance? These would affect the values in the API as well.

If not: At the moment the `measuredPower` is only set to a default of `-59` or, if it is an iBeacon, whatever is available in the [iBeacon data](https://github.com/mKeRix/room-assistant/blob/f8e5c74debc872b0efcc3cb242fc011aa37864b0/src/integrations/bluetooth-low-energy/i-beacon.ts#L16). The `txPowerLevel` is ignored since [this commit](https://github.com/mKeRix/room-assistant/commit/a4425bae4adda9dcead5be1434464348100cfcf9), but this may have been a mistake as I don't remember why I did this.

**Comment by marrold** [comment]
> Are you setting tag overrides for the measuredPower on the nodes by any chance? These would affect the values in the API as well.

Ah yes, you're right! 

> If not: At the moment the measuredPower is only set to a default of -59 or, if it is an iBeacon, whatever is available in the iBeacon data. The txPowerLevel is ignored since this commit, but this may have been a mistake as I don't remember why I did this.

Ah ok, interesting. I didn't know it was being overriden. I'll keep this in mind
