### ISSUE TITLE
UUID is incorrectly read; always set as the mac for BLE scanner

### ISSUE THREAD

**Issue by gruijter** [mKeRix/room-assistant#28]
I have a raspberry pi zero W with the following in local.json:
```{
  "ble": {
    "enabled": true,
    "channel": "room_presence",
    "max_distance": 30,
    "whitelist": [],
    "use_mac": false,
    "system_noise": 0.01,
    "measurement_noise": 3,
    "update_frequency": 0
  }
}
```

But I always get the mac as ID, and never the UUID:
```
{"id":"f69e2d86fe4a","name":"MI Band 2","rssi":-74,"distance":13.58329930223587}
```

I really need to get the UUID and not the (ever changing) MAC. What am I doing wrong?

**Comment by mKeRix** [comment]
The config looks right to me. It might be related to how the band handles its advertisements (specifically if it tries to prevent tracking). Since Google didn't give me any meaningful results, it would probably make sense to look at the raw data that is received. I will try to get that in as an option asap so we can debug this further.
