### ISSUE TITLE
BLE state only 'true' or 'false'?

### ISSUE THREAD

**Issue by triblondon** [mKeRix/room-assistant#297]
Hiya and thanks for providing this great app for the HA community.

I am trying to add room assistant to my Home Assistant setup today, using two instances (one rPi Zero W, and one as an HA addon via supervisor), both configured to use BLE integrations.  My problem is that the devices are published to MQTT as just a state which is `true` or `false`, when I thought the whole point of RA was to know which room they are in!

Output from the Zero W:

```
10/10/2020, 4:32:09 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral ffff4001396f with ID ffff4001396f and RSSI -47
10/10/2020, 4:32:09 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/ble-ffff4001396f-tracker/state
```

So then I headed over to my HA integrations page and clicked CONFIGURE on the MQTT integration, where I can listen to that topic:

![image](https://user-images.githubusercontent.com/1735391/95659188-281bdc80-0b17-11eb-84ea-beb5baf35cc2.png)

But it's just a series of "true" and "false" statuses, not "bedroom" and "livingroom" as I expected.  I saw that there are other topics I could potentially listen to [in the code here](https://github.com/mKeRix/room-assistant/blob/031d1b687b58fb6b357b9cc0c89c3edcf6907ee8/src/integrations/home-assistant/entity-config.ts#L28-L31) and the only one that seems to be emitting any messages is `/status` which is always "online".

Secondary questions (if I may!):

* It seems like autodiscovery is a non-starter because [HA doesn't support `device_tracker` entities being discovered](https://www.home-assistant.io/docs/mqtt/discovery/)?  Is that correct? If so, is there any way to allow RA to present topics in a way that *is* discoverable, eg. a [sensor](https://www.home-assistant.io/integrations/sensor.mqtt/)?
* If it's necessary to set up each device tracker at the HA end individually, then I'd be tempted to have RA tell HA about *all* discovered beacons, so that if I want to add/remove a device I only have to do it in one place (in HA config).  However in my house there is a LOT of BLE noise that I can't identify, so would that cause a performance problem / is it a terrible idea?
* When you run RA from systemctl, where are the logs sent to?  When I run it that way, it doesn't stay running so I'm assuming it hits an error that I would see in the log.
* The HASSIO addon version of RA seems to not be able to do discovery of other instances (as mentioned in the docs) but I also can't get it to use a hostname to find the other instance either - got a DNS timeout `EAI_AGAIN` and a NodeJS stacktrace logged in the addon log and the process quit.  I could only connect the cluster using an IP address.  Is that the best practice?

**Comment by triblondon** [comment]
Oh, interestingly, if I use the API at <ipaddress>:6415/api and execute a get entities call, I get TWO entries in the output for each entity, for example:

```
  {
    "attributes": {},
    "id": "ble-ffff30012e7d-tracker",
    "name": "iTAG            ",
    "distributed": true,
    "state": true
  },
  {
    "attributes": {
      "distance": 2.2,
      "lastUpdatedAt": "2020-10-10T16:28:18.263Z"
    },
    "id": "ble-ffff30012e7d",
    "name": "iTAG             Room Presence",
    "distributed": true,
    "distances": {
      "bedroom": {
        "lastUpdatedAt": "2020-10-10T16:28:18.263Z",
        "distance": 2.2,
        "outOfRange": false
      }
    },
    "timeout": 5,
    "measuredValues": {
      "bedroom": {
        "rssi": -65.84874892756734,
        "measuredPower": -59
      }
    },
    "state": "bedroom"
  },
```

The first of these seems to be what is being published to MQTT, but the second seems to have the room location on it.  So I tried listening to the `room-assistant/device_tracker/ble-ffff4001396f/state` topic instead of `room-assistant/device_tracker/ble-ffff4001396f-tracker/state`, but no messages, so I guess that's not right.

**Comment by mKeRix** [comment]
room-assistant registers most of its sensors via auto-discovery in Home Assistant. The device trackers are actually the only ones that aren't auto discovered due to the limitations in HA - hence the warning message. You should be able to find the other topics by listening to `room-assistant/#` in the HA MQTT panel.

Double check that your discovery is on in the MQTT options of HA and that you use the default base topic (I think it's `homeassistant`). Alternatively, you can setup the sensors manually yourself in the YAML config. You should see the devices appear in the MQTT integration, each one with a couple different entities bound to it.

Running it via systemctl lets the system take care of the log data, you should be able to view it completely by typing `journalctl -u room-assistant.service`.

The HA add-on issue regarding DNS is unfortunately a bit out of the realm of room-assistant - this is managed by the HA supervisor, which in turn is limited by Docker. Depending on the installation type and a bunch of other factors some things may or may not work as you realized. In your case using the IP is a valid option, if possible I would give at least one of your instances/Pis a DHCP reservation or a static IP. That ensures that the instances can still find each other, even if an IP changes in your network.

**Comment by triblondon** [comment]
OMG bingo.  I was led astray by the console text that said "Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/ble-ffff4001396f-tracker/state".  I thought that must mean that I should set my discovery domain to `room-assistant`.  I just changed to to `homeassistant` and the devices and entities popped up!
