### ISSUE TITLE
iPhone not detected as device

### ISSUE THREAD

**Issue by nickelnine** [mKeRix/room-assistant#324]
**Describe the bug**
Configured Bluetooth Classic integration with both OnePlus 6 Android device MAC and iPhone 12 iOS 14.1 device MAC. Only Android device is being picked up by Room Assistant and shown in Home Assistant, the iPhone is being ignored. Running GET /entities only shows the Android device also

**To reproduce**
Configure iPhone 12 iOS 14.1

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

No errors as Room Assistant starts up fine.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.xx.yy:1883'
bluetoothClassic:
  minRssi: -1
  interval: 30
  addresses:
    - '64:A2:F9:3C:8D:E9'
    - 'FC:66:CF:68:50:4C'

```

**Expected behavior**
iPhone to show up as a device in MQTT integration in Home Assistant and iPhone to appear in GET /entities response.

**Environment**
 - room-assistant version: 2.11.2
 - installation type: NodeJS
 - hardware: RPi 3b
 - OS: Raspbian Buster Lite

**Additional context**
I also paired the iPhone to the OnePlus 6 to kick start device tracking as suggested https://github.com/mKeRix/room-assistant/issues/270#issuecomment-676302916 but that did not work.

**Comment by mKeRix** [comment]
Did you have an iPhone running on room-assistant before and then just add the iPhone 12 now, or are you just now setting up room-assistant?

What's the output of `sudo hcitool cc <iphone-mac>`? Also double check that you're using the Bluetooth MAC, as it's quite close to the WiFi MAC.

**Comment by nickelnine** [comment]
Hi @mKeRix, I did have an iPhone 8 before which was running fine on room-assistant. It's now an iPhone 12 Pro I'm replacing it with. 

The output of `sudo hcitool cc <iphone-mac>` is `Can't create connection: Input/output error`

I did double check and I am using the Bluetooth MAC under General > About section.

**Comment by mKeRix** [comment]
Hm... do you have any Bluetooth headphones or some smart watch you could pair to the iPhone by any chance? I'm not sure if it makes a difference, I just thought the behavior may be a bit different.

Other than that, is room-assistant able to connect to your iPhone as long as you are in the Bluetooth settings screen (where it says "your phone is now visible as xyz" at the top) with the display on?

**Comment by gadric** [comment]
I seems to have the same problem. I switched from an iPhone 7 to a iPhone 12 Pro and the tracking is often interrupted. It switchs to ```not_home``` after the iPhone has been inactive (lock screen) for a couple of seconds. This did not happened with the iPhone 7

**Comment by gadric** [comment]
Since a couple of days I am facing a related problem to this. 

I have a rpi4 and and rpi0 working with NPM room assistant without any problems and room assistant is detecting an iPhone 12 Pro and and Google Pixel 5 without any issues. However, on a Intel NUC with room assistant as Hasslochs Addon, the detection does not work. It seems to work if I ssh to the machine and start ```hcitool cc <mac address>```

But after a while, the room assistant as hassio Addon stop detecting the phones. Sometimes, it sporadically detecting, but stops are a couple of seconds again.

**Comment by mKeRix** [comment]
I would recommend to switch to BLE for iPhones starting with v2.13.0 and will therefore close this issue.

**Comment by gadric** [comment]
Thanks for the info. I will check it in next days. 

Do you also have a guide for Android phones (e.g., how to retrieve BLE UUID on Android phones)?

**Comment by mKeRix** [comment]
I don't have one myself, but there are multiple apps for Android that can broadcast as iBeacons. You can use those and then track the iBeacon ID in room-assistant like you normally would. There is also an open issue at #472 for improving the user experience of this. If you end up setting up with one of the already available apps on Android please feel free to post it as a guide on here or make a PR to add it to the docs... it's common question which I can never quite answer because I have no device to test it on. 😅
