### ISSUE TITLE
Room-assistant reports these values

### ISSUE THREAD

**Issue by yeralin** [mKeRix/room-assistant#37]
{  
   "id":"fda50693a4e24fb1afcfc6eb07647826-10065-26049",
   "uuid":"fda50693a4e24fb1afcfc6eb07647826",
   "major":10065,
   "minor":26049,
   "rssi":-72,
   "distance":215547485467.13068,
   "accuracy":1.7051123055198094e+37,
   "measuredpower":-3,
   "proximity":"far"
}

How should I read distance? Why is it so high? Why "proximity" is "far"? As far as I know rssi=-72 is about 2 meters distance.

I guess I need to play around with system_noise and measurement_noise values?

**Comment by mKeRix** [comment]
Hi @yeralin,

reported distance should be read as meters. The values you are seeing are of course incorrect though - this is likely due to the "measured power" of the iBeacon being set incorrectly. Can you adjust this for the beacons you're using? The correct value to set here is the average rssi value you see when you place the beacon exactly 1 meter away from the receiver. Currently this seems to be set to -3 on your beacon, normal values are usually between 60 and 80.

You can easily do this with room-assistant as your receiver by just looking at the outputted values once the beacon is placed down 1 meter from the machine you're running it on. Then use the configuration app to set the measured power value. Some apps also have this function included as an automated process, e.g. Radbeacons.

If this doesn't help or you don't know how to do this: which beacons are you using?

**Comment by yeralin** [comment]
Thank you. But I ended up calibrating it by modifying txPower.

**Comment by mKeRix** [comment]
txPower = measured power, two terms for the same thing. Glad you figured it out though :)
