### ISSUE TITLE
Room assistant stopped working on an rpi 3 b+

### ISSUE THREAD

**Issue by grinco** [mKeRix/room-assistant#390]
I have a few raspberries around the apartment running room assistant. In one of the rooms room assistant stopped working (no idea when), assuming after an update. I tried multiple kernel versions, and node versions. Reinstalled room-assistant - same results. I can discover ble devices using hcitool, so hardware works just fine. Is there anything I can do to troubleshoot the issue? Running room-assistant in verbose mode didn't add any value.

I tried replicating as much configuration, package versions, kernel, firmware and other raspberry pi options across the one that works and the one that doesn't with no luck. It runs fine on a 3 B, and fails to discover any beacons on 3 B+. I've noticed that B+ has BT5.0 while 3B is 4.1 if that helps. I'm kind of out of ideas in terms of troubleshooting, especially that I confirmed that bluetooth hardware is working using standard Linux tools.

**Comment by grinco** [comment]
Tried running room-assistant in docker and it works just fine, so it's not the hardware, kernel, firmware or anything else - most probably update to node.js

**Comment by mKeRix** [comment]
As a note for the future: Since you mentioned that you updated/re-installed NodeJS - did you re-run the ``sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`` command after that? Each time that NodeJS is updated these permissions need to be re-granted unfortunately. If that isn't done it will just stop seeing any BLE devices if you don't run room-assistant as root (which is what all the guides recommend).
