### ISSUE TITLE
Supported BLE beacon hardware?

### ISSUE THREAD

**Issue by nunofgs** [mKeRix/room-assistant#4]
I'm considering going this route for room presence tracking. Do you know what hardware is supported with this package?

It might be helpful to list a few of the supported/tested hardware combinations on the README.

~~As a quick test, I downloaded the "Estimote" iOS app which has a [virtual ibeacon](https://community.estimote.com/hc/en-us/articles/200908836-How-to-turn-my-iPhone-into-a-Virtual-Beacon-) functionality but room-assistant never picked it up.

Any idea why?~~

Got the above to work. I was just subscribing on the wrong topic in MQTT.

**Comment by mKeRix** [comment]
Sorry for the long radio silence! I tested this software with a bunch of virtual beacon apps on Android as well as the RadBeacon Dot. The tested hardware list is a really good idea, I will add it to the README this weekend. I'll also download the Estimote app and try to find root cause of that issue.

**Comment by nunofgs** [comment]
Thanks. I ended up getting Estimote to work. Turns out I was just subscribing to the wrong topic.

**Comment by mKeRix** [comment]
I added a note regarding this in the BLE component documentation - I hope this is informative enough. :)
