### ISSUE TITLE
Monitor doesn’t require pairing 

### ISSUE THREAD

**Issue by genebean** [mKeRix/room-assistant#474]
**Describe the bug**

https://www.room-assistant.io/guide/#why-not says monitor requires pairing... this is inaccurate. No pairing is needed. It tracks phones and such simply by having their real MAC address. 

**Additional context**

https://github.com/andrewjfreyer/monitor has all the details of this.

**Comment by mKeRix** [comment]
It can track phones being somewhere in reach without pairing, but it does need pairing to track RSSI (required for room level presence). See the header "RSSI Tracking" in their README - unfortunately I don't think I can link to it directly due to how they formatted it. For me this means that the closest feature set in monitor to what room-assistant offers requires pairing, which is why I would consider our docs correct.
