### ISSUE TITLE
Cant disable Heat Map gridEye

### ISSUE THREAD

**Issue by beatified** [mKeRix/room-assistant#607]
I have 4 rpi0w's all with gridEye's and I have found that they are struggling with creating the image for the heatmap.

So I saw the ```enabled:``` option for heatmap and tried to set it to false but it doesn't seem to do anything.

Here is my local.yml
```global:
  instanceName: ra_living_room
  integrations:
    - homeAssistant
    - gridEye
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.20.8:1883'
  mqttOptions:
    username: user
    password: password
gridEye:
  deltaThreshold: 3
  heatmap:
    enabled: false
bluetoothClassic:
  minRssi: -20
  addresses:
    - '00:00:00:13:d7:03'
    - '00:00:00:d4:95:c0'
cluster:
  networkInterface: wlan0
  autoDescovery: true
  port: 6425
```
Am I missing something or is it possible it's not working as desired?

**Comment by beatified** [comment]
Just a thought. Have you ever considered having only one instances of RA create the images? Since at least one of the machines (most likely the host for HA) would likely have enough processing power to do the processing for all the heatmaps. Who knows maybe that's not a good idea just thought it couldn't hurt to ask.

**Comment by mKeRix** [comment]
Hm, I successfully use that option in my setup, although that is for the Omron D6T. Is the heatmap actually still being generated? Or is it just the leftover image from before you turned it off? The camera entity won't actually be removed from HA atm, so you'll just have a "ghost" camera entity there with an old state.

Generating images on a "powerful" instance would be cool, but isn't super easy to implement in room-assistant while considering all the edge cases, which is why I haven't implemented anything in that direction yet. I'm happy to accept contributions for it though, if someone feels up to the challenge :)

**Comment by beatified** [comment]
Yeah I am sure that its still updating the heatmap image. I figured that the camera might stick around so I waited for it to see if it would update and sure enough it did.

I wish I had the expertise to help out in that way but unfortunately I don't.
