### ISSUE TITLE
Other sensors

### ISSUE THREAD

**Issue by stripeyhorse** [mKeRix/room-assistant#62]
Any change we could get more Sensors added. Eg Temp?

SHT3x
code here: https://github.com/alwint3r/sht31-node

Would love to get rid of my ESP32/8266 etc.

im thinking 1 Rasp pi zero per room for bluetooth and hopefully temp, light , CO2 tracking

**Comment by mKeRix** [comment]
Definitely possible! The code is kept fairly extensible for that very reason.

I'm on vacation till the end of this month, so I won’t do much in that time. After that I’ll try to get my hands on one or a couple of these sensors and setup an integration. You can of course also code the component yourself and submit a PR if you know some JavaScript :)

**Comment by stripeyhorse** [comment]
revisiting this one. ive looked at the code. maybe its just me but im confused. could we get an example sensor maybe and then i can try and edit that and test locally?

Im thinking SHT21x , TLS2561 , BME/P280 , BME680 etc. As since these are spread out over my house why not use them for temp etc tracking

**Comment by mKeRix** [comment]
It's hard to give an example sensor - it really depends on how it works. Most common sensors have some sort of Javascript library available on npm that does the heavy lifting I think. If you want a reference implementation in room-assistant you can check out the [gpio service](https://github.com/mKeRix/room-assistant/blob/master/services/gpio.service.js), I think it is the closest to what you're looking for. I am also planning on developing an integration for D6T sensors that could be used as integration reference. Otherwise you'll have to be patient, I will check out the list of sensors you described and see if there's something that I can get my hands on easily!
