### ISSUE TITLE
Incompatible with plant sensors on Hass IO

### ISSUE THREAD

**Issue by jptrsn** [mKeRix/room-assistant#63]
I have Hass IO installed on a Raspberry Pi 3, and I'm running room assistant on two Raspberry Pi Zero Ws. The system works really well, but when I try to use the room assistant add-on in combination with Hass IO, I can't get my Mi Flora sensor readings.

The miflora plant platform is a component that uses ble to [read sensor data.](https://www.home-assistant.io/components/sensor.miflora/).

Any chance that these two components could play nicely together? Alternatively, any chance of reporting the GATT characteristics to the relevant mqtt topics in place of the mi flora component?

**Comment by mKeRix** [comment]
I'm not sure if we can get the two components to work together correctly in Hass.io, might be that the Bluetooth scanning capability is limited to 1 container/process. Integrating the Flora sensors into room-assistant could be possible though, since there already is the Home Assistant example to work with. Just don't have anything to test it with sadly!

**Comment by jptrsn** [comment]
Okay, no problem. I'm working on an ESP32 version of this concept (that would be room assistant running on an ESP32), so I can attempt to bring it in that way.
