### ISSUE TITLE
Is it possible to use wildcards in whitelist? 

### ISSUE THREAD

**Issue by hemantkamalakar** [mKeRix/room-assistant#66]
Hello,
I have been using room-assistant along with home-assistant. I have Minew beacons and wanted to check if it is possible to use wildcards in whitelist  configuration.
I have to update the whitelist in the config file for every new beacon. It would be great if it is possible to have the whitelist like `"whitelist": ["ac:23:3f:23:??:??"]`
Minew beacon MAC address starts with `ac:23:3f:23.`

**Comment by mKeRix** [comment]
Sadly this is not possible in the current version (1.0) of room-assistant. if you want to try and develop this functionality yourself you can find the relevant code [here](https://github.com/mKeRix/room-assistant/blob/master/mixins/whitelist.mixin.js). Should be a pretty simple change actually!

Otherwise I'll take this on my features to develop list and will get back around to it once I find the time.

**Comment by hemantkamalakar** [comment]
Thanks a lot for your reply.
Please put it on the features to develop list. I am closing this one now.

**Comment by mKeRix** [comment]
Reopening this for tacking purposes. :)

**Comment by mKeRix** [comment]
Feature has been added in version 1.1.0, you can now make your whitelist be a list of regex patterns to match against!
