### ISSUE TITLE
Failed to search for companion app when no app is installed

### ISSUE THREAD

**Issue by aguilaair** [mKeRix/room-assistant#675]
**Describe the bug**
I tried the companion app a few days ago with room-assistant but later uninstalled it, and since then from time to time I get: `error - BluetoothLowEnergyService: Failed to search for companion app at tag xxxxxxx: timed out` even though the device is no longer added to the configuration file

**To reproduce**
Add a companion app, let it discover it and the delete it.

**Relevant logs**

```text
Apr 29 09:51:16 raspberrypi room-assistant[671]: 29/04/2021, 09:51:16 - info - BluetoothLowEnergyService: Attempting app discovery for tag xxxxx

Apr 29 09:51:32 raspberrypi room-assistant[671]: 29/04/2021, 09:51:32 - error - BluetoothLowEnergyService: Failed to search for companion app at tag xxxxx: timed out
```

**Relevant configuration**
(the tag it is attempting to discover is not in the config)
```yaml
bluetoothLowEnergy:
  allowlist:
    - yyyyyyyyy
  maxDistance: 10
```

**Expected behavior**
Should not be attempting to connect

**Environment**
 - room-assistant version: 2.16.0
 - installation type: NodeJS
 - hardware: Pi 4
 - OS: Linux

**Comment by mKeRix** [comment]
So the way the app logic works is by connecting to all Apple devices advertising a certain service in the BLE packets. Apple's custom way of doing this doesn't make this unique, so another app could technically advertise using the same bit and cause room-assistant to connect and look for the unique ID. This also means that if you have an app installed somewhere, but not configured, it will still connect and look because room-assistant won't know what the unique ID is until it actually checked.

That being said, since you uninstalled the app this shouldn't happen anymore of course (unless you have another device in reach that advertises the app or some app that uses the same bit, but that's unlikely). Have you tried restarting the phone? Maybe the advertisement data isn't cleaned by iOS on uninstall.

**Comment by aguilaair** [comment]
Yep, still getting the timeouts even after a restart, even other devices are recognised as a companion app (and they have never installed the companion app), I can try seeing if they have an app in common, but I can't think of one right now.
