### ISSUE TITLE
basic-install.sh: not found

### ISSUE THREAD

**Issue by arsaboo** [mKeRix/room-assistant#706]
**Describe the bug**
I tried updating Roomassistant, but I keep getting this error about `basic-install.sh: not found`

```bash
pi@study:~ $ sudo npm i --global --unsafe-perm room-assistant
dd: unrecognized operand ‘to’
Try 'dd --help' for more information.
/usr/local/bin/npm: 2: /usr/local/bin/npm: basic-install.sh: not found
```
I tried reinstalling both nodejs and npm, but the error persists

**Relevant configuration**

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: Rapberry Pi 
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**

**Comment by Nihvel** [comment]
What OS are you using? I have installed Room Assistant twice in the last 4 days, on 2x Raspberry Pi Zero W running Raspberry Pi OS Lite (32 bit) as per doc. says, and didn't encounter the error you described.

**Comment by mKeRix** [comment]
This looks like something is off with your npm installation - I would recommend to re-install NodeJS and then try installing room-assistant again. If you are on a Pi Zero W and you used the install script from the docs you can just re-run it to do this. On other platforms you should be able to re-install using `apt-get`.

Since this isn't a bug with room-assistant I'll close this issue, but feel free to keep commenting and I'll try to help further.
