### ISSUE TITLE
Android Detect

### ISSUE THREAD

**Issue by soloam** [mKeRix/room-assistant#73]
Hello, I installed the service and it's working, I can see the mqtt being populated. I tried to capture my android phone, but it seams that the UUID is allays changing, also I can't get by mac add. Is this possible? to capture a Android phone?

Thank you

**Comment by mKeRix** [comment]
You can with some specific beacon apps - which also allow you to set ids manually. I played around with it quite a while ago though and since switched to iOS, so I don't remember the names of the apps I used. Best idea is to just download some of the beacon apps on the Play Store and try them out - some of them support running in the background :)
