### ISSUE TITLE
Machine Learning support

### ISSUE THREAD

**Issue by nagydavid** [mKeRix/room-assistant#815]
First of all thank you @mKeRix  for creating this solution, its amazing.
**Is your feature request related to a problem? Please describe.**
Machine learning support: I know it has been discussed, but I decided to work on it a little bit. Due to I am working with this, I am giving it a try.

**Describe the solution you'd like**
I setup my home with 4 pi0 and 2 pi 4b, every device running the docker version. Right now I am trying to setup a proper data pipeline to record and label the different rssi value based on the BLE integration. If I can do that, with a 10 min exercise everybody can create at home their own training and scoring dataset, and self calibrate for their own tracked device(s).

I am planning to test 2-3 different algorithm, which hopefully not be computationally expensive to run on a raspberry pi. (e.g RandomForest, LSTM(maybe), SVM)

**Describe alternatives you've considered**
no alternatives
**Additional context**
In order to this to work I need a constant connection to the RPis.  However I need to extend the range of some of the RPI4 because it seems to drop if I am more than 7m away and 2 wall between.  
![image](https://user-images.githubusercontent.com/10994218/125774051-8b20fc54-85df-4c02-997b-94beabe264ba.png)

So the question would be, which usb dongle would you recommend for RPi4 and RPI0W

**Comment by mKeRix** [comment]
I have no specific recommendations for dongles, especially since the availability varies wildly across countries. For the most part you should be good if the dongle is either specifically marketed as Linux compatible or has reviews stating that it is.

I'd love to hear about your results! For tracking purposes I'd like to stick to one issue for discussion though, which would be #507. For that reason I'll close this issue.
