### ISSUE TITLE
Changing topic?

### ISSUE THREAD

**Issue by c-scoot** [mKeRix/room-assistant#84]
Hi, I can’t seem to work out how to change the topic that is used when sent to MQTT? I can see the messages ok if I subscribe to all topics, but would like to be more specific

Thanks!

Craig

**Comment by mKeRix** [comment]
Hey there,

I'm sure you've figured it out by now, but for anyone stumbling across this in the future: the MQTT topic is set in one of two ways, depending on whether Home Assistant auto discovery is enabled or not.

If it is not enabled, you can customize it by changing the `room` and `channel` settings in the config. The data is sent CHANNEL/ROOM in this case.

If auto discovery is enabled you can use the same settings to modify the channel, plus `discoveryType`. The channel is then named homeassistant/DISCOVERYTYPE/ROOM/CHANNEL as per Home Assistant guidelines.

**Comment by wojtek14a** [comment]
Hi,
I'm wondering if this configuration is still valid because I can't get it to work nor can I find it in docs.

I want to mix up ESP32-MQTT-room and your _amazing_ piece of software (I have a couple of RPis as well as ESP32 all around my home) but to do so I need them to publish to the same topic. I have them configured as stated in HA and ESP32-MQTT-room docs:
```yaml
sensor:
  - platform: mqtt_room
    device_id: "some MAC address here"
    name: 'yada yada yada'
    state_topic: 'room_presence'
    timeout: 60
    away_timeout: 120
```

Is it possible to make room-assistant publish all detected BLE devices to the same topic in a format described [here](https://www.home-assistant.io/integrations/mqtt_room/)?
I could switch my ESPs to publish to `room-assistant/sensor` but room-assistant doesn't seem to have a subtopic for each room it rather has for each device.

I will be grateful for your guidance!

**Comment by wojtek14a** [comment]
@mKeRix ?

**Comment by mKeRix** [comment]
room-assistant switched away from the MQTT Room integration in Home Assistant for a few reasons:

- better control of how the state is determined
- less messages being sent to MQTT (wish of the community)
- auto-discovery in Home Assistant

The use case of mixing different software via MQTT Room honestly has not occurred to me before you mentioned it. For now what you can do is use room-assistant v1.x (available via git tags, not on npm!) instead and open a new feature request issue for bringing back MQTT Room Presence support.

**Comment by SeLLeRoNe** [comment]
Ah!
I've been going nuts because I couldn't get MQTT Room to work!

I still don't get (except using a template sensor) how to get the sensor integrated in HA if AutoDiscovery is not enabled.

I would aswell appreciate if mqtt_room was still compatible, if that will not be the case, you might want to let HA Staff know (or change the docs yourself) since it state it is :)

![image](https://user-images.githubusercontent.com/9599441/103922236-c1a55b00-5113-11eb-9231-7bf14e401d6b.png)

**Comment by mKeRix** [comment]
I just opened #432 to track adding this back. I wanted to overhaul the publishing a bit anyway, which should hopefully make this easy to implement again.

@SeLLeRoNe You can get it integrated using the normal [MQTT sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) configurations. You can copy the configuration from the auto discovery messages (found under `homeassistant/+` in MQTT) into your configuration files. Alternatively, you can also build the configuration manually - the relevant topics are all under `room-assistant/+`.

**Comment by SeLLeRoNe** [comment]
Yep, that's what I mean by template (sorry, I just forgot the orrect naming).

I usually block on MQTT level topics I don't want to use, so I don't hafve the homeassistant one and mqtt discovery :) 

Thanks for now, I'll follow #432 :)

A
