### ISSUE TITLE
PR to ignore noise on Grideye AMG8833

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#886]
**Is your feature request related to a problem? Please describe.**

I've just picked up an AMG8833 for Grideye use and overall think it's really good.  Three problem I'm seeing if that some values come through incorrectly , either as 0, 0.25 or 0.5. Not in the same squares, bit distributed around per report. Quick Google suggests others have seen this problem too and filter out these erroneous readings.

The issue with these readings is that they bring down the overall mean, so if you get 5 in one report your chance of a false positive increases a lot.
**Describe the solution you'd like**

I've been testing a fix that ignores values under 1, replacing them with the last 'valid' value.

**Describe alternatives you've considered**

I'm thinking that default behavior remains the same, and that we could have a config option, either that:
  -- replaces values below the specified number. E g . User specifies 1 in config so we replace those with nearest valid value as per my period of concept
  -- specify a list of numbers to replace, e.g. 0,0.25,0.5
  -- specify a list ranges that should be replaced, e.g 0..1

In the first instance the first one would work fine for this use case. So I'm thinking of potentially submitting a PR with that, with a view to considering the other 2 should the need arise .

Are you happy for me set that up? Any thoughts welcome.

**Additional context**

**Comment by mKeRix** [comment]
Sounds good to me! Happy to review and help with a PR on that. For the use case in room-assistant I doubt people are using it to measure temperatures below the freezing point, so the simple approach 1 should be a good first iteration. As you mentioned, that would also leave room to extend into other approaches should the need arise.

Would probably be a good idea to add a little troubleshooting section to the GridEYE docs as well, just so that other people that stumble into the problem can find the option quickly.

**Comment by mKeRix** [comment]
Fixed with #891
